version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "📦 Installing dependencies..."
      - npm install -g aws-cdk
      - yum install -y jq
      - cd backend && npm install && cd ..
      - cd backend/cdk && npm install && cd ../..
      - cd frontend && npm install && cd ..

  pre_build:
    commands:
      - echo "🔧 Pre-build phase started"
      - aws sts get-caller-identity
      - export CDK_DEFAULT_ACCOUNT=${AWS_ACCOUNT}
      - export CDK_DEFAULT_REGION=${AWS_REGION}
      - |
        if [ "$ACTION" = "deploy" ]; then
          cd backend
          npm run build || echo "Build had errors"
          rm -rf lambda-bundle
          mkdir -p lambda-bundle
          cp -r dist/* lambda-bundle/
          cp package.json lambda-bundle/
          cd lambda-bundle
          npm install --production --omit=dev
          cd ../..
          cd backend/cdk
          npx tsc
          cd ../..
        fi

  build:
    commands:
      - cd backend/cdk
      - |
        if [ "$ACTION" = "deploy" ]; then
          cdk bootstrap aws://${AWS_ACCOUNT}/${AWS_REGION}
          cdk synth --context environment=${ENVIRONMENT} --context bedrockAgentId=${BEDROCK_AGENT_ID} --context bedrockAgentAliasId=${BEDROCK_AGENT_ALIAS_ID} --context region=${AWS_REGION}
          cdk deploy --all --require-approval never --context environment=${ENVIRONMENT} --context bedrockAgentId=${BEDROCK_AGENT_ID} --context bedrockAgentAliasId=${BEDROCK_AGENT_ALIAS_ID} --context region=${AWS_REGION} --outputs-file ../../cdk-outputs.json
        fi
      - cd ../..
      - |
        if [ "$ACTION" = "deploy" ] && [ -f "cdk-outputs.json" ]; then
          cat cdk-outputs.json
          WS_URL=$(jq -r '.WebSocketStack.WebSocketURL' cdk-outputs.json 2>/dev/null || jq -r '.WebSocketStack.WebSocketApiUrl' cdk-outputs.json 2>/dev/null || echo "")
          API_URL=$(jq -r '.RestApiStack.RestApiUrl' cdk-outputs.json 2>/dev/null || jq -r '.RestApiStack.PLTWRestApiEndpoint98DE8254' cdk-outputs.json 2>/dev/null || echo "")
          BUCKET=$(jq -r '.FrontendStack.FrontendBucketName' cdk-outputs.json 2>/dev/null || echo "")
          DIST_ID=$(jq -r '.FrontendStack.CloudFrontDistributionId' cdk-outputs.json 2>/dev/null || echo "")
          POOL_ID=$(jq -r '.CognitoStack.UserPoolId' cdk-outputs.json 2>/dev/null || echo "")
          CLIENT_ID=$(jq -r '.CognitoStack.UserPoolClientId' cdk-outputs.json 2>/dev/null || echo "")
          echo "WebSocket=${WS_URL}"
          echo "API=${API_URL}"
          echo "Bucket=${BUCKET}"
          if [ -n "$BUCKET" ]; then
            cd frontend
            echo "REACT_APP_ENVIRONMENT=${ENVIRONMENT}" > .env
            echo "REACT_APP_REGION=${AWS_REGION}" >> .env
            echo "REACT_APP_WEBSOCKET_URL=${WS_URL}" >> .env
            echo "REACT_APP_API_URL=${API_URL}" >> .env
            echo "REACT_APP_USER_POOL_ID=${POOL_ID}" >> .env
            echo "REACT_APP_USER_POOL_CLIENT_ID=${CLIENT_ID}" >> .env
            npm run build
            if [ -d "out" ]; then
              aws s3 sync out/ s3://${BUCKET}/ --delete
            elif [ -d "build" ]; then
              aws s3 sync build/ s3://${BUCKET}/ --delete
            fi
            if [ -n "$DIST_ID" ]; then
              aws cloudfront create-invalidation --distribution-id ${DIST_ID} --paths "/*"
            fi
            cd ..
          fi
        fi

  post_build:
    commands:
      - |
        if [ "$ACTION" = "deploy" ] && [ -f "cdk-outputs.json" ]; then
          echo "DEPLOYMENT COMPLETE"
          jq '.' cdk-outputs.json
        fi

artifacts:
  files:
    - "**/*"

cache:
  paths:
    - "backend/node_modules/**/*"
    - "backend/cdk/node_modules/**/*"
    - "frontend/node_modules/**/*"
