version: 0.2

# PLTW Chatbot - CodeBuild Build Specification
# Matches actual repo structure: backend/cdk/ and backend/src/handlers/

env:
  variables:
    NODE_VERSION: "20"
  exported-variables:
    - AWS_REGION
    - ENVIRONMENT

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11
    commands:
      - echo "📦 Installing dependencies..."
      - echo "Node version:" $(node --version)
      - echo "NPM version:" $(npm --version)

      # Install AWS CDK
      - npm install -g aws-cdk
      - echo "CDK version:" $(cdk --version)

      # Install backend dependencies (includes Lambda handlers)
      - echo "Installing backend dependencies..."
      - cd backend
      - npm install
      - cd ..

      # Install CDK dependencies
      - echo "Installing CDK dependencies..."
      - cd backend/cdk
      - npm install
      - cd ../..

      # Install frontend dependencies
      - echo "Installing frontend dependencies..."
      - cd frontend
      - npm install
      - cd ..

  pre_build:
    commands:
      - echo "🔧 Pre-build phase started on $(date)"
      - echo "ACTION=${ACTION}"
      - echo "ENVIRONMENT=${ENVIRONMENT}"
      - echo "AWS_REGION=${AWS_REGION}"
      - echo "BEDROCK_AGENT_ID=${BEDROCK_AGENT_ID:0:10}..."
      - echo "BEDROCK_AGENT_ALIAS_ID=${BEDROCK_AGENT_ALIAS_ID:0:10}..."

      # Configure AWS credentials
      - aws sts get-caller-identity

      # Export environment variables for CDK
      - export CDK_DEFAULT_ACCOUNT=${AWS_ACCOUNT}
      - export CDK_DEFAULT_REGION=${AWS_REGION}

      - |
        if [ "$ACTION" = "deploy" ]; then
          echo "🔨 Building Lambda functions..."
          
          # Build Lambda handlers
          cd backend
          
          # Build TypeScript Lambda functions if build script exists
          if grep -q '"build"' package.json; then
            echo "Running backend build script..."
            npm run build
          fi
          
          # Check if lambda-bundle directory was created
          if [ -d "lambda-bundle" ]; then
            echo "✅ Lambda bundle created"
            ls -lh lambda-bundle/
          elif [ -d "dist" ]; then
            echo "✅ Dist directory created"
            ls -lh dist/
          else
            echo "⚠️  No lambda-bundle or dist found, Lambda code may be in src/"
          fi
          
          cd ..
          
          echo "✅ Lambda build completed"
        fi

  build:
    commands:
      - echo "🚀 Build phase started on $(date)"
      - cd backend/cdk

      - |
        if [ "$ACTION" = "deploy" ]; then
          echo "📦 Bootstrapping CDK (if needed)..."
          cdk bootstrap aws://${AWS_ACCOUNT}/${AWS_REGION} || echo "Already bootstrapped"
          
          echo "📦 Synthesizing CDK stack..."
          cdk synth \
            --context environment=${ENVIRONMENT} \
            --context bedrockAgentId=${BEDROCK_AGENT_ID} \
            --context bedrockAgentAliasId=${BEDROCK_AGENT_ALIAS_ID} \
            --context region=${AWS_REGION}
          
          echo "🚀 Deploying CDK stack..."
          cdk deploy --all \
            --require-approval never \
            --context environment=${ENVIRONMENT} \
            --context bedrockAgentId=${BEDROCK_AGENT_ID} \
            --context bedrockAgentAliasId=${BEDROCK_AGENT_ALIAS_ID} \
            --context region=${AWS_REGION} \
            --outputs-file ../../cdk-outputs.json
          
          echo "✅ CDK deployment completed"
          
          # Display outputs
          if [ -f ../../cdk-outputs.json ]; then
            echo "📋 CDK Outputs:"
            cat ../../cdk-outputs.json
          fi
          
        elif [ "$ACTION" = "destroy" ]; then
          echo "🔥 Destroying CDK stack..."
          cdk destroy --all \
            --force \
            --context environment=${ENVIRONMENT} \
            --context bedrockAgentId=${BEDROCK_AGENT_ID} \
            --context bedrockAgentAliasId=${BEDROCK_AGENT_ALIAS_ID} \
            --context region=${AWS_REGION}
          
          echo "✅ CDK destruction completed"
        fi

      - cd ../..

  post_build:
    commands:
      - echo "✨ Post-build phase started on $(date)"

      - |
        if [ "$ACTION" = "deploy" ]; then
          # Deploy frontend
          echo "🌐 Deploying frontend..."
          
          # Get S3 bucket and CloudFront distribution from CDK outputs
          if [ -f cdk-outputs.json ]; then
            STACK_NAME="PltchatbotStack-${ENVIRONMENT}"
            
            # Try to extract frontend bucket (without jq)
            FRONTEND_BUCKET=$(cat cdk-outputs.json | grep -o '"FrontendBucketName"[^"]*"[^"]*"' | tail -1 | cut -d'"' -f4 || echo "")
            
            if [ -z "$FRONTEND_BUCKET" ]; then
              # Try alternative output keys
              FRONTEND_BUCKET=$(cat cdk-outputs.json | grep -o '"WebsiteBucket[^"]*"[^"]*"[^"]*"' | tail -1 | cut -d'"' -f4 || echo "")
            fi
            
            if [ -n "$FRONTEND_BUCKET" ]; then
              echo "Deploying to S3 bucket: $FRONTEND_BUCKET"
              
              cd frontend
              
              # Build Next.js frontend
              echo "Building Next.js frontend..."
              npm run build
              
              # Deploy to S3
              if [ -d ".next" ]; then
                # Next.js static export
                if [ -d "out" ]; then
                  echo "Deploying Next.js static export..."
                  aws s3 sync out/ s3://${FRONTEND_BUCKET}/ --delete
                else
                  echo "⚠️  Next.js build completed but no 'out' directory found"
                  echo "Make sure next.config.js has 'output: export'"
                fi
              elif [ -d "build" ]; then
                # React build output
                aws s3 sync build/ s3://${FRONTEND_BUCKET}/ --delete
              elif [ -d "dist" ]; then
                # Vite/other build output
                aws s3 sync dist/ s3://${FRONTEND_BUCKET}/ --delete
              else
                echo "⚠️  No build output directory found (out/build/dist)"
              fi
              
              # Invalidate CloudFront if distribution exists
              CF_DISTRIBUTION=$(cat ../cdk-outputs.json | grep -o '"CloudFrontDistribution[^"]*"[^"]*"[^"]*"' | tail -1 | cut -d'"' -f4 || echo "")
              if [ -n "$CF_DISTRIBUTION" ]; then
                echo "Invalidating CloudFront cache..."
                aws cloudfront create-invalidation \
                  --distribution-id ${CF_DISTRIBUTION} \
                  --paths "/*" || echo "CloudFront invalidation failed"
              fi
              
              cd ..
              
              echo "✅ Frontend deployed"
            else
              echo "⚠️  Frontend bucket not found in CDK outputs"
              echo "Available outputs:"
              cat cdk-outputs.json
            fi
          else
            echo "⚠️  No cdk-outputs.json found"
          fi
          
          echo ""
          echo "🎉 ============================================="
          echo "🎉 DEPLOYMENT COMPLETED SUCCESSFULLY!"
          echo "🎉 ============================================="
          echo ""
          
          # Display URLs in user-friendly format
          if [ -f cdk-outputs.json ]; then
            echo "📋 Deployment URLs:"
            echo "==================="
            
            # Extract outputs (works without jq)
            WEBSOCKET_URL=$(cat cdk-outputs.json | grep -o '"WebSocketApiUrl"[^"]*"[^"]*"' | tail -1 | cut -d'"' -f4 || echo "Not available")
            REST_API_URL=$(cat cdk-outputs.json | grep -o '"RestApiUrl"[^"]*"[^"]*"' | tail -1 | cut -d'"' -f4 || echo "Not available")
            FRONTEND_URL=$(cat cdk-outputs.json | grep -o '"FrontendUrl"[^"]*"[^"]*"' | tail -1 | cut -d'"' -f4 || echo "Not available")
            
            if [ -z "$FRONTEND_URL" ] || [ "$FRONTEND_URL" = "Not available" ]; then
              # Try CloudFront URL
              FRONTEND_URL=$(cat cdk-outputs.json | grep -o '"CloudFrontUrl"[^"]*"[^"]*"' | tail -1 | cut -d'"' -f4 || echo "Not available")
            fi
            
            echo "🖥️  Frontend:    $FRONTEND_URL"
            echo "🔌 WebSocket:   $WEBSOCKET_URL"
            echo "🔗 REST API:    $REST_API_URL"
            echo ""
            
            echo "📋 Full CDK Outputs:"
            cat cdk-outputs.json
            echo ""
          fi
          
        elif [ "$ACTION" = "destroy" ]; then
          echo ""
          echo "🎉 ============================================="
          echo "🎉 DESTRUCTION COMPLETED SUCCESSFULLY!"
          echo "🎉 ============================================="
          echo ""
        fi

      - echo "Build completed on $(date)"

artifacts:
  files:
    - "**/*"
  name: pltw-chatbot-build-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - "backend/node_modules/**/*"
    - "backend/cdk/node_modules/**/*"
    - "frontend/node_modules/**/*"
